title:              Hairul Blog
email:              hairulabkar@gmail.com
description:        Blog Terkait Info Teknology Internet Marketing
author:             Hairul Abkar
baseurl:            "/startbootstrap-clean-blog-jekyll"
url:                "https://startbootstrap.github.io"

# Social Profiles
twitter_username:   HairulAbkar
github_username:    HairulAbkar
facebook_username:  StartBootstrap
instagram_username: HairulAbkar 
linkedin_username:  HairulAbkar

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
